
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jakarta@123
      POSTGRES_DB: amane
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: sh -c "npx prisma db push &&
                    npx prisma generate &&
                    npx tsx prisma/seed.ts &&
                    npm run dev"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:Jakarta%40123@db:5432/amane?schema=public
      PUBLIC_ENV__API_HOST: https://api-data.hcml.co.id/
      PUBLIC_ENV__APP_SECRET: 45tereyhdfst6785ergdfy574wsfgty654es3543trwrtgrer
      PUBLIC_ENV__UPLOAD_FOLDER: AMANE
      API_HOST: https://api-data.hcml.co.id/
      APP_SECRET: 45tereyhdfst6785ergdfy574wsfgty654es3543trwrtgrer
      UPLOAD_FOLDER: AMANE
      PRISMA_MIGRATE_SKIP_GENERATE: 1
      NODE_ENV: development
    ports:
      - '3012:3012'
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  db_data: 