import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

export async function seedDetailLocation() {
  console.log('\n🌱 Starting Location Detail seeding...')

  const data = [
    { id: 79, description: "n/a" },
    { id: 1, description: "OUTSIDE AREA" },
    { id: 2, description: "Cellar Deck - Control Room" },
    { id: 3, description: "Mezzanine" },
    { id: 4, description: "Control Room" },
    { id: 5, description: "Cellar Deck" },
    { id: 6, description: "Top of Jacket" },
    { id: 7, description: "Main Deck" },
    { id: 8, description: "Cover Warehouse" },
    { id: 9, description: "PORTACAMP" },
    { id: 10, description: "GMS Area" },
    { id: 11, description: "EQUIPMENT STORAGE SHELTER" },
    { id: 12, description: "MBH Mezzanine" },
    { id: 13, description: "MDA Sub Cellar Deck" },
    { id: 14, description: "MBH Cellar Deck" },
    { id: 15, description: "MAC WHP" },
    { id: 16, description: "FILTER COALESCER" },
    { id: 17, description: "CLOSE DRAIN" },
    { id: 18, description: "SPT ROOM" },
    { id: 19, description: "MCC" },
    { id: 20, description: "WORKSHOP" },
    { id: 21, description: "METERING" },
    { id: 22, description: "PIG RECEIVER" },
    { id: 23, description: "MBH Jacket" },
    { id: 24, description: "Gudang HRGA" },
    { id: 25, description: "0" },
    { id: 26, description: "#N/A" },
    { id: 27, description: "Line 1" },
    { id: 28, description: "25th Floor" },
    { id: 29, description: "Mail Room" },
    { id: 30, description: "Open Yard" },
    { id: 31, description: "EDG" },
    { id: 32, description: "MV Room" },
    { id: 33, description: "CCR" },
    { id: 34, description: "POTABLE WATER TANK" },
    { id: 35, description: "NEAR ANALYZER SHELTER" },
    { id: 36, description: "Filling Room" },
    { id: 37, description: "SECURITY ROOM" },
    { id: 38, description: "PANTRY" },
    { id: 39, description: "HCML Office Room" },
    { id: 40, description: "SCM - Sarah P" },
    { id: 41, description: "Main deck" },
    { id: 42, description: "Sampang" },
    { id: 43, description: "Gas Export" },
    { id: 44, description: "KO DRUM" },
    { id: 45, description: "INCOMING" },
    { id: 46, description: "CCR " },
    { id: 47, description: "BATTERY ROOM" },
    { id: 48, description: "CO2 SKID" },
    { id: 49, description: "WC SPT ROOM" },
    { id: 50, description: "MDA Mezzanine" },
    { id: 51, description: "COPY CENTER" },
    { id: 52, description: "Mezzanine " },
    { id: 53, description: "MDA Jacket" },
    { id: 54, description: "STAFF ROOM" },
    { id: 55, description: "VENT STACK" },
    { id: 56, description: "MV ROOM" },
    { id: 57, description: "SHELTER AREA" },
    { id: 58, description: "STAFF AREA" },
    { id: 59, description: "MANAGER ROOM" },
    { id: 60, description: "Panaboard di Office (Lt 25)" },
    { id: 61, description: "FPU, Doctor Room" },
    { id: 62, description: "MBH" },
    { id: 63, description: "MBH Sub Cellar Deck" },
    { id: 64, description: "STORAGE CONTAINER" },
    { id: 65, description: "HSSE 25th Floor" },
    { id: 66, description: "Mezzanine/ Control Room" },
    { id: 67, description: "Line 2" },
    { id: 68, description: "MDA" },
    { id: 69, description: "FPU  " },
    { id: 70, description: "NEAR MV Room" },
    { id: 71, description: "PLN ROOM" },
    { id: 72, description: "LOBBY" },
    { id: 73, description: "MEETING ROOM" },
    { id: 74, description: "MDA/MBH" },
    { id: 75, description: "Subsurface File Area" },
    { id: 76, description: "HEAD ROOM" },
    { id: 77, description: "Raas 2" },
    { id: 78, description: "Pantry Lt.24" },
  ]

  console.log(`🔢 Total location records to insert: ${data.length}`)

  const result = await prisma.detailsLocation.createMany({
    data,
    skipDuplicates: true,
  })

  console.log(`✅ Inserted ${result.count} new records (skipped duplicates).`)
  console.log('✅ LocationDesc seeding complete.\n')
}
